theme: jekyll-theme-dinky
# theme: jekyll-theme-hacker
# theme: jekyll-theme-midnight
# theme: jekyll-theme-minima
# theme: jekyll-theme-minimal
title: *Curriculum vitae*
description: Bookmark this to keep an eye on my project updates!
